name: 'flask-restx-backend'

services:
  flask-restx:
    container_name: flask-restx
    build: .
    ports:
      - "5002:5000"
    volumes:
      - .:/usr/src/app
      # - /data1/OTA/firmware:/firmware
      - C:/firmware:/firmware
    environment:
      FLASK_DEBUG: "0"
      FLASK_ENV: production
    networks:
      - iot-stack_default
    env_file:
      - production.env

    # depends_on:
    #   - postgres

#   postgres:
#     container_name: postgres
#     image: postgres:latest
#     environment:
#       POSTGRES_DB: iot_db
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: password
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
  # redis:
  #     image: redis:latest
  #     container_name: redis
  #     ports:
  #       - "6379:6379"
  #     volumes:
  #       - redis_data:/data

networks:
  iot-stack_default:
    external: true
# volumes:
#   postgres_data:
#   redis_data:
#     driver: local

