name: 'flask-restx-backend'

services:
  flask-restx:
    container_name: flask-restx
    build: .
    command: flask run --host=0.0.0.0
    ports:
      - "5002:5000"
    volumes:
      - .:/usr/src/app
      - /data1/OTA/firmware:/firmware
    environment:
      FLASK_ENV: development
      DATABASE_URI: postgresql://iot_backend:3Jp8VJyia7ECaj@postgres:5432/iot_db
      VALID_KEY: XXV7lnIse9q4YGA11pXA
      TEMI1500_FIRMWARE_DIR: /firmware/temi1500
      LILYGOS3_FIRMWARE_DIR: /firmware/lilygos3

    # depends_on:
    #   - postgres

#   postgres:
#     container_name: postgres
#     image: postgres:latest
#     environment:
#       POSTGRES_DB: iot_db
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: password
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
