"""Update migration

Revision ID: 81b046c735f6
Revises: 
Create Date: 2024-07-20 17:09:07.488677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81b046c735f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_temphumi_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp_limit', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('humi_limit', sa.String(length=255), nullable=True))
        batch_op.alter_column('sensor_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_temphumi_data', schema=None) as batch_op:
        batch_op.alter_column('sensor_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('humi_limit')
        batch_op.drop_column('temp_limit')

    # ### end Alembic commands ###
