"""update tables

Revision ID: b5c5b737d6eb
Revises: 
Create Date: 2024-07-14 18:00:50.205912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5c5b737d6eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_temphumi_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sensor_id', sa.String(length=255), nullable=True))
        batch_op.drop_column('device_name')
        batch_op.drop_column('humidity')
        batch_op.drop_column('temperature')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_temphumi_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('humidity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('device_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('sensor_id')

    # ### end Alembic commands ###
