"""update tables

Revision ID: e44136637d41
Revises: 
Create Date: 2024-07-14 19:27:51.523863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e44136637d41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('esp_data_lilygo_s3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org', sa.String(length=255), nullable=False),
    sa.Column('dept', sa.String(length=255), nullable=False),
    sa.Column('room', sa.String(length=255), nullable=False),
    sa.Column('line', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('u_id', sa.String(length=255), nullable=False),
    sa.Column('device_type', sa.String(length=255), nullable=False),
    sa.Column('firm_ver', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('u_id')
    )
    op.create_table('esp_temi1500_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org', sa.String(length=255), nullable=False),
    sa.Column('dept', sa.String(length=255), nullable=False),
    sa.Column('room', sa.String(length=255), nullable=False),
    sa.Column('line', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('u_id', sa.String(length=255), nullable=False),
    sa.Column('device_type', sa.String(length=255), nullable=False),
    sa.Column('firm_ver', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('u_id')
    )
    op.create_table('sensor_temphumi_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('u_id', sa.String(length=255), nullable=False),
    sa.Column('h_slope', sa.Float(), nullable=True),
    sa.Column('t_slope', sa.Float(), nullable=True),
    sa.Column('h_intercept', sa.Float(), nullable=True),
    sa.Column('t_intercept', sa.Float(), nullable=True),
    sa.Column('sensor_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['u_id'], ['esp_data_lilygo_s3.u_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('u_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_temphumi_data')
    op.drop_table('esp_temi1500_data')
    op.drop_table('esp_data_lilygo_s3')
    # ### end Alembic commands ###
